version: '3.7'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=chat
      - POSTGRES_USER=grygoryz
      - POSTGRES_PASSWORD=kdnvhdHYa63hDK
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
        
  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

volumes:
  postgres:
  redis:
