version: '3.7'

services:
  app:
    image: $APP_IMAGE_SHA
    environment:
      - PORT=3000
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - NODE_ENV=production
      - LOG_RESPONSE_BODY
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis
